name: Flutter - Android Build Dev

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup HOME CONTROLLER File
        run: echo "HOME_CONTROLLER_FILE=lib/controllers/home_controller.dart" >> $GITHUB_ENV     

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.6'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Auto format the dart code
        run: dart format .

      - name: Verify the dart code is formatted
        run: dart format --output=none --set-exit-if-changed .  

      - name: Analyze the dart code
        run: flutter analyze --fatal-warnings

      - name: Build APK
        run: flutter build apk --debug --build-name=1.0.0 --build-number=1